### ISSUE TITLE
Base64 strings within url()

### ISSUE THREAD

**Issue by maxkrieger** [joshwnj/style-attr#2]
Not sure if this is still being maintained, but if there could be a way to ignore semicolons within a `url()` closure, it would avoid picking up a base64 uri ([which uses both semicolons and colons](https://en.wikipedia.org/wiki/Data_URI_scheme#Examples)).

**Comment by joshwnj** [comment]
Hi @maxkrieger, thanks for raising the issue. Can you please check whether #3 fixes your case, and I'll merge and publish a patch if it does.

**Comment by maxkrieger** [comment]
Works perfectly! Thanks a bunch!

**Comment by joshwnj** [comment]
published v1.0.2
